### ISSUE TITLE
Fix missing text

### ISSUE THREAD

**Issue by ootsun** [matter-labs/zksync-web-v2-docs#123]
I spotted multiple typos in the doc and I wanted to share the info with you.

**In fundamentals/zkSync.md**
1) This paragraph shouldn't be there. It is duplicated. 
![image](https://user-images.githubusercontent.com/25452154/196288828-11984d42-f787-4112-a93a-699757f916a8.png)

2) A bullet is missing : 
![image](https://user-images.githubusercontent.com/25452154/196288923-71705316-bec3-4fcc-ad61-d0aa0710b690.png)

3) Incomplete sentence : 
![image](https://user-images.githubusercontent.com/25452154/196289010-81b6427d-0167-4b19-8c52-ba4c9f5d309e.png)

**Comment by uF4No** [comment]
Thanks for the heads-up @ootsun. We're updating our docs every day so we'll make sure to include these fixes.

**Comment by ootsun** [comment]
Nice! I catched those too : 
**In transactions/aa.md**
1. The step number are incorrect
![image](https://user-images.githubusercontent.com/25452154/196495553-655ef0d9-abf8-4742-9b98-182764571682.png)

2. This part might be erased
![image](https://user-images.githubusercontent.com/25452154/196495783-7a91e7e9-460c-4ff9-a244-0cc032328fe1.png)

**Comment by uF4No** [comment]
These fixes will be included in PR #108

**Comment by uF4No** [comment]
fixes released
