### ISSUE TITLE
404 of edit the page

### ISSUE THREAD

**Issue by merlincdj** [matter-labs/zksync-web-v2-docs#218]
https://v2-docs.zksync.io/dev/troubleshooting/docs-contribution/docs.html#contribute-to-documentation

The reference link `edit the page` is 404.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/39942523/207556173-c5ac4d56-89a2-4937-b07e-9c9703da9a81.png">

**Comment by krofax** [comment]
@merlincdj this has been fixed, you can check it again, I'm closing this issue.
